name: Ping Supabase

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 */3 * *"   # every 3 days at 08:00 Lagos time

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Supabase awake
        run: curl https://jxdycvtemkmfzriqvsrd.supabase.co/rest/v1/ || true
