name: Ping Supabase

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  workflow_dispatch:          # manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://supabase.com/dashboard/project/jxdycvtemkmfzriqvsrd/ || true
